trigger:
- main

variables:
- group: pythongroup          # contains ACR_LOGIN_SERVER, IMAGE_NAME, etc.
- name: imageTag
  value: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

stages:
# -------------------------------
# Stage 1: Build & Push to ACR (with approval before push)
# -------------------------------
- stage: BuildAndPush
  displayName: Build and Push Docker Image to ACR
  jobs:
  - deployment: BuildPushJob
    displayName: Build & Push Docker Image
    environment: prod   # 👈 Add approval in Azure DevOps → Environments
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          # Login to ACR
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: acr-pythoncode   # ACR service connection

          # Build and Push image after approval
          - script: |
              IMAGE=$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(imageTag)
              echo "Building Docker image: $IMAGE"
              docker build -t $IMAGE .
              echo "Pushing Docker image to ACR..."
              docker push $IMAGE
            displayName: Build and Push Docker Image
