trigger:
- main

variables:
- group: acr-vars  # Variable group with ACR_USERNAME, ACR_PASSWORD, ACR_LOGIN_SERVER, IMAGE_NAME

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndPush
  jobs:
  - job: DockerBuildPush
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(ACR_LOGIN_SERVER)

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        tags: |
          $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId)

    - task: Docker@2
      displayName: Push Image to ACR
      inputs:
        command: push
        tags: |
          $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId)

- stage: DeployToVM
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'linux-vm-ssh'
        runOptions: inline
        inline: |
          docker login $(ACR_LOGIN_SERVER) -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
          docker pull $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId)
          docker stop app || true && docker rm app || true
          docker run -d --name app -p 80:8080 $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId)
